### ISSUE TITLE
Eigenvalue opt example

### ISSUE THREAD

**Issue by t-mitchell** [sun-umn/PyGRANSO#25]
Need to change:

- [x]  \lambda to \Lambda (lowercase to uppercase) (Typically, \Lambda uppercase denotes the spectrum, while \lambda lowercase denotes an eigenvalue.)
- [x] "$\\lambda(\\cdot)$ is the eigenvalue of $\\cdot$," to "$\\Lambda(\\cdot)$ is the spectrum of a square matrix,"
- [x] "$\\alpha$ is the maximum real part of eigenvalues of $M$." to "$\\alpha(\cdot)$ is the spectral abscissa of a square matrix, i.e., the maximum real part of its eigenvalues."
- [x] For imaginary part, \Im, in papers, I generally redefine this from the standard symbol to just "Im", e.g., "Im(A+BXC)", as I think this is usually much clearer.  But this is a debatable suggestion.

**Comment by Buyun-Liang** [comment]
Just made the initial public release
