### ISSUE TITLE
Posting announcement for PyGRANSO

### ISSUE THREAD

**Issue by Buyun-Liang** [sun-umn/PyGRANSO#31]
Machine Learning News: https://groups.google.com/g/ml-news

SIAM: 
https://www.siam.org/membership/activity-groups/detail/computational-science-and-engineering
https://www.siam.org/membership/activity-groups/detail/data-science
https://www.siam.org/membership/activity-groups/detail/imaging-science
https://www.siam.org/membership/activity-groups/detail/optimization

**Comment by t-mitchell** [comment]
Question: do you and Ju think it would be better to make announcements this week or until a preprint of the next paper with more comparisons is available?  Not sure myself.

**Comment by Buyun-Liang** [comment]
From Ju: 

> For those places we have announced, I think it's fine. For opt experts, probably it's better if we have more detailed comparisons

So we will only post it on Machine Learning News this week, and delay the announcement on SIAM until when we get out the next icml preprint

**Comment by Buyun-Liang** [comment]
Besides that, there are several research groups shown interest in our package two weeks ago. Can we schedule a Zoom meeting tomorrow to discuss the follow-up emails?

**Comment by t-mitchell** [comment]
> Besides that, there are several research groups shown interest in our package two weeks ago. Can we schedule a Zoom meeting tomorrow to discuss the follow-up emails?

Yes, today or tomorrow is possible.  Our usual 10am your time works for me, but I can also meet at other times too.

**Comment by Buyun-Liang** [comment]
Sorry, not able to meet at the usual time today. Any time after 12:00 (19:00 your time) today, and any time tomorrow work for me

**Comment by t-mitchell** [comment]
19:00 my time works

**Comment by Buyun-Liang** [comment]
Invitation sent

**Comment by Buyun-Liang** [comment]
Just prepared a short version response to those who replied me shortly. See page 3 of Google doc "NCVX/PyGRANSO Announcement". I feel it's still too detailed.

**Comment by t-mitchell** [comment]
I didn't think the the length/detail was a problem, but I did edit both the page 2 and page 3 versions.  I think both are better, but see what you think.

**Comment by Buyun-Liang** [comment]
Yes, looks good to me

**Comment by Buyun-Liang** [comment]
We just got the arxiv page updated https://arxiv.org/abs/2111.13984. I'll send these emails tomorrow morning.
