### ISSUE TITLE
[Bug Fix] PyGranso Package does not allow multiple gpu parallelism

### ISSUE THREAD

**Issue by HengyueL** [sun-umn/PyGRANSO#37]
File path:  ...../pygranso/private/isTorchDevice.py/isTorchDevice
Line 50:

Original Code: tf = (x == torch.device('cuda') or x == torch.device('cpu'))

Issue: this line prohibits user from specifying the gpu device to compute. 
E.g, if a user set opt.device = torch.device("cuda:0"), pygranso will cast a runtime error.

Fix: change the original line into:
tf = (isinstance(x, torch.device))

**Comment by Buyun-Liang** [comment]
fixed
